steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        OPENAI_API_KEY=$(gcloud secrets versions access latest --secret="OPENAI_API_KEY")
        export OPENAI_API_KEY
        docker compose -f docker-compose.yaml up --build
