steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Remove the cached Docker image
        docker rmi -f gcr.io/cloud-builders/docker || true

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Access the secret and set the environment variable
        OPENAI_API_KEY=$(gcloud secrets versions access latest --secret="OPENAI_API_KEY")
        # Export the variable for Docker Compose to use
        export OPENAI_API_KEY
        # Navigate to the directory containing docker-compose.yaml
        cd "DreamScribe/All Project Code and Components"
        # Run Docker Compose with the environment variable
        docker-compose up

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '-c', '-d', '.', 'gs://your-bucket-name']

availableSecrets:
  secretManager:
  - versionName: projects/dingletronics/secrets/OPENAI_API_KEY/versions/latest
    env: OPENAI_API_KEY

options:
  logging: CLOUD_LOGGING_ONLY
